id: PA8646F34
initial_creation_type: input
source_metadata:
  title: Dhammapada
  language: en
  volumes:
    add3f15cbd9245f48f9ebbd5883d82b1:
      title: 'CIII_Chapter 21: Pakiṇṇavaggo'
      base_file: 'CIII_Chapter 21: Pakiṇṇavaggo.txt'
      work_id: W752AAEE7
    cd53c556134845a9bebd50388e7e12fd:
      title: 'CIII_Chapter 22: Nirayavaggo'
      base_file: 'CIII_Chapter 22: Nirayavaggo.txt'
      work_id: WD53D5750
    89c5d0edf30b4660a46a68e1f849812c:
      title: 'CIII_Chapter 23: Nāgavaggo'
      base_file: 'CIII_Chapter 23: Nāgavaggo.txt'
      work_id: W045050E8
    8952e29cc23b4725bead985ac61d0853:
      title: 'CIII_Chapter 24: Taṇhāvaggo'
      base_file: 'CIII_Chapter 24: Taṇhāvaggo.txt'
      work_id: WCAC0BC7A
    d7ec2d068c0f4ecea0606ccda29526a6:
      title: 'CIII_Chapter 25: Bhikkhuvaggo'
      base_file: 'CIII_Chapter 25: Bhikkhuvaggo.txt'
      work_id: W3CF3F0AC
    70892f5d4dc34a83ba748f45e4f9b8ac:
      title: 'CIII_Chapter 26: Brāhmaṇavaggo'
      base_file: 'CIII_Chapter 26: Brāhmaṇavaggo.txt'
      work_id: WB3C3BFB1
    df493f0a2c90454793e5084b8ee55136:
      title: 'CII_Chapter 11: Jarāvaggo'
      base_file: 'CII_Chapter 11: Jarāvaggo.txt'
      work_id: W2DECB0DD
    e62df2786a41497bbe19dadd9bef0b36:
      title: 'CII_Chapter 12: Attavaggo'
      base_file: 'CII_Chapter 12: Attavaggo.txt'
      work_id: W89CF59A6
    3d2e4581419f42be850a09337844d275:
      title: 'CII_Chapter 13: Lokavaggo'
      base_file: 'CII_Chapter 13: Lokavaggo.txt'
      work_id: WB40A6F2D
    045ffc3ab0b545ad80ed58711f3b59cb:
      title: 'CII_Chapter 14: Buddhavaggo'
      base_file: 'CII_Chapter 14: Buddhavaggo.txt'
      work_id: W4AE08B62
    3dabb7a991d241c7ba1ea3f6f36b613a:
      title: 'CII_Chapter 15: Sukhavaggo'
      base_file: 'CII_Chapter 15: Sukhavaggo.txt'
      work_id: WA13C3ACD
    c7aa73bc1b404d0b96e9dfda91764e1c:
      title: 'CII_Chapter 16: Piyavaggo'
      base_file: 'CII_Chapter 16: Piyavaggo.txt'
      work_id: WFE974955
    07d83ac19f1f4b219bee1bb595e229df:
      title: 'CII_Chapter 17: Kodhavaggo'
      base_file: 'CII_Chapter 17: Kodhavaggo.txt'
      work_id: WC4FCD99A
    118239d7bdba4f4bbb1c0fd33c69f8ae:
      title: 'CII_Chapter 18: Malavaggo'
      base_file: 'CII_Chapter 18: Malavaggo.txt'
      work_id: W27DE8789
    e71ed4e567154e87b672e12be0f1b464:
      title: 'CII_Chapter 19: Dhammaṭṭhavaggo'
      base_file: 'CII_Chapter 19: Dhammaṭṭhavaggo.txt'
      work_id: W2BDBE8EE
    32a1fa72bef24048a1144767e65abdb2:
      title: 'CII_Chapter 20: Maggavaggo'
      base_file: 'CII_Chapter 20: Maggavaggo.txt'
      work_id: W26803280
    42afb52e31914b49b1c53a8ce9e6d420:
      title: CIV_Additional Chinese verses
      base_file: CIV_Additional Chinese verses.txt
      work_id: W93D9EF41
    7bdf11c6841146adbb60acdaa9822a6d:
      title: CIV_Additional Gāndhārī verses
      base_file: CIV_Additional Gāndhārī verses.txt
      work_id: WCEC0719E
    4ebfcc94a74d45bf90a858d546a3215a:
      title: CIV_Additional Prakrit verses
      base_file: CIV_Additional Prakrit verses.txt
      work_id: W08EB921B
    1898db82f66b46449d23a6f585333d65:
      title: 'CI_Chapter 10: Daṇaḍavaggo'
      base_file: 'CI_Chapter 10: Daṇaḍavaggo.txt'
      work_id: W6663EDB5
    640a78cccdce4e82b9ac54f986b43fcd:
      title: 'CI_Chapter 1: Yamakavaggo'
      base_file: 'CI_Chapter 1: Yamakavaggo.txt'
      work_id: W09BD53D3
    9444824d895a45938ff54f87f5ad89bc:
      title: 'CI_Chapter 2: Appamādavaggo'
      base_file: 'CI_Chapter 2: Appamādavaggo.txt'
      work_id: WE5D8FE64
    4759a05b6dc74297a2e5ae9cf10cf33c:
      title: 'CI_Chapter 3: Cittavaggo'
      base_file: 'CI_Chapter 3: Cittavaggo.txt'
      work_id: W35839485
    4af193c69afc47cc9bc216149d460278:
      title: 'CI_Chapter 4: Pupphavaggo'
      base_file: 'CI_Chapter 4: Pupphavaggo.txt'
      work_id: WEFF85818
    21d2fcae97154ff7b4634e7a913bfd90:
      title: 'CI_Chapter 5: Bālavaggo'
      base_file: 'CI_Chapter 5: Bālavaggo.txt'
      work_id: W9916CF0B
    c813894788e94c58a7abebd69abc2c98:
      title: 'CI_Chapter 6: Paṇḍitavaggo'
      base_file: 'CI_Chapter 6: Paṇḍitavaggo.txt'
      work_id: WAB47EABA
    fd83f967365949859d677aaf2907de96:
      title: 'CI_Chapter 7: Arahantavaggo'
      base_file: 'CI_Chapter 7: Arahantavaggo.txt'
      work_id: W1C010EDC
    73e3d84d5c0840cc97a4aec5f8dd3a83:
      title: 'CI_Chapter 8: Sahassavaggo'
      base_file: 'CI_Chapter 8: Sahassavaggo.txt'
      work_id: W0E6EBEBE
    146adba781a34c5d9f5aa82167e93a23:
      title: 'CI_Chapter 9: Pāpavaggo'
      base_file: 'CI_Chapter 9: Pāpavaggo.txt'
      work_id: W88DFDF14
    8754d41a21ec45f2920adace100a8e70:
      title: Colophon
      base_file: Colophon.txt
      work_id: W61A159BF
    6ec9d7907e8c494cb250000d53484f09:
      title: Preface
      base_file: Preface.txt
      work_id: W480C9599
    307e491a2fa940329fc0ccb69db5038c:
      title: Title
      base_file: Title.txt
      work_id: WDB71E853
  chapter_to_tile:
    CI: Chapters 1-10
    CII: Chapters 11-20
    CIII: Chapters 21-26
    CIV: Additional verses not in the Pāli edition
created_at: '2022-03-01T23:17:11.405037'
last_modified_at: '2022-03-01T23:17:11.405047'
